version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=bazar
      - POSTGRES_USER=bazar
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
