# Generated by Django 4.1 on 2022-09-30 00:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_delete_adssubscriber_delete_subscription'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('paid_sum', models.PositiveIntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber', to='advertisement.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Подписка объявления',
                'verbose_name_plural': 'Подписки объявлений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('icon', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.AddField(
            model_name='adssubscriber',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.subscription', verbose_name='Подписка'),
        ),
    ]
