# Generated by Django 4.1 on 2022-09-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_adssubscriber_subscription_delete_orderpayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adssubscriber',
            old_name='paid_sum',
            new_name='pg_amount',
        ),
    ]
