# Generated by Django 4.1 on 2022-09-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_favorite_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsSubscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
